[system]
# Load language from environment variable(It is set by the hook)
language = "en"
api_keys = []
encrypt_key = "your_secret_key"

# Server Configurations
[service.web]
host = "0.0.0.0"
port = 5670

[service.web.database]
type = "sqlite"
path = "pilot/meta_data/dbgpt.db"

[rag.storage]
[rag.storage.vector]
type = "Chroma"
persist_path = "pilot/data"

# Model Configurations
[models]
[[models.llms]]
name = "${env:LLM_MODEL_NAME:-Qwen/QwQ-32B}"
provider = "${env:LLM_MODEL_PROVIDER:-proxy/openai}"
api_base = "${env:OPENAI_API_BASE:-https://api.hyperbolic.xyz/v1}"
api_key = "${env:OPENAI_API_KEY}"
max_tokens = "${env:MAX_TOKENS:-1024}"
temperature = "${env:TEMPERATURE:-0.6}"
top_p = "${env:TOP_P:-0.95}"

[[models.embeddings]]
name = "${env:EMBEDDING_MODEL_NAME:-Qwen/QwQ-32B}"
provider = "${env:EMBEDDING_MODEL_PROVIDER:-proxy/openai}"
api_url = "${env:EMBEDDING_MODEL_API_URL:-https://api.hyperbolic.xyz/v1/embeddings}"
api_key = "${env:OPENAI_API_KEY}"
